### ISSUE TITLE
Code Release Timeline / Data Availability

### ISSUE THREAD

**Issue by MichalMalyska** [inQbator-eviCore/LLM_section_identifiers#1]
Is there any timeline on code being published or in particular on the labelled versions of your data / labelling script ?
Or any plans around what would be included ? 

It would be good to contribute a bunch more patterns to MedSpaCy - and especially since you guys seem to also have propriety data, getting permission to share the Regex you use on that data and adding that to MedSpaCy / opensourcing it here so I can try and add it there.

**Comment by singhay** [comment]
@MichalMalyska Hi Michal, thank you for reaching out. 

The annotations are now uploaded. Please check them out.

As for MedSpaCy, we think it's a fantastic idea and plan to integrate our work into the MedSpaCy library in the upcoming weeks.

Regards,
inQbator AI team
